### ISSUE TITLE
lsbinit header in nodemanager.erb

### ISSUE THREAD

**Issue by Raskil** [biemond/biemond-orautils#10]
Hi Biemond,

the nodemanager.erb templates from orautis provides two lsbinit comment blocks with different dependencys:

```#!/bin/sh
#
### BEGIN INIT INFO
# Provides:        nodemanager
# Required-Start:
# Required-Stop:
# Default-Start:    2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:    WebLogic Nodemanager
### END INIT INFO

# nodemgr Oracle Weblogic NodeManager service
#
# chkconfig:   345 99 15
# description: Oracle Weblogic NodeManager service
#

### BEGIN INIT INFO
# Provides: nodemgr
# Required-Start: $network $local_fs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Oracle Weblogic NodeManager service.
# Description: Starts and stops Oracle Weblogic NodeManager.
### END INIT INFO``
```
Is there a reason for multiple blocks?
The specification at http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html mentions only a single block. So I'm not sure if multiple blocks are allowed and how they are handled.

I'm asking because we are trying to set uo dependencies in other services we use and it seems like the doubled lsbinit block is causing trouble for specifing dependencys on the nodemanager script.

regards

Benny

**Comment by biemond** [comment]
Oh that is strange and not wanted.

Will fix it

**Comment by Raskil** [comment]
I can send you a PR if that helps.

**Comment by biemond** [comment]
perfect, send me a PR
