### ISSUE TITLE
Support for WL 12.2.x

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orautils#22]
See this: https://github.com/biemond/biemond-orawls/issues/404

**Comment by adamjk-dev** [comment]
Looks like pieces of interest:

https://github.com/biemond/biemond-orautils/blob/master/manifests/nodemanagerautostart.pp#L17-L52
https://github.com/biemond/biemond-orautils/blob/master/templates/nodemanager.erb#L58
https://github.com/biemond/biemond-orautils/blob/master/templates/nodemanager.erb#L72

**Comment by biemond** [comment]
fixed and push a new version

**Comment by adamjk-dev** [comment]
Should this case also handle 12.2.1.1. and 12.2.1.2?

**Comment by biemond** [comment]
all 12.2.1 versions should work the same and I don't expect any other behaviour in all the versions.
so use 1221 as version for all 12.2 editions. 

probably I can implement > < etc but this is more clear and better to understand.

**Comment by adamjk-dev** [comment]
Hrmph.... I presume so .... hehe
