### ISSUE TITLE
Hardcoded AdminServer name in template

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orautils#3]
https://github.com/biemond/biemond-orautils/blob/2020d3c06c8425f3a4730fe9441e3be16512f95e/templates/wls/showStatus.sh.erb#L20

So, this assumes the AdminServer name is 'AdminServer' , instead of using the parameter that was passed in: https://github.com/biemond/biemond-orautils/blob/master/manifests/init.pp#L21

**Comment by biemond** [comment]
Thanks 

I will fix it.

**Comment by biemond** [comment]
Done,

Can you also check this for me.

thanks

**Comment by adamjk-dev** [comment]
Just tested this by changing the name to 'admin' and it appears to work.

```
# pwd
/opt/scripts/wls
# ./showStatus.sh 
 __________________________________
|              NAME|  STATUS|   PID|
|__________________|________|______|
|             admin|  Online|  9196|
|__________________|________|______|
|       NodeManager|  Online|  8502|
|__________________|________|______| 
```
